<?php
/**
 * Generated configuration file
 * Generated by: phpMyAdmin 5.2.1 setup script
 * Date: Thu, 16 Jan 2025 02:20:05 +0000
 */

$cfg['DefaultLang'] = 'en';
$i=0;
$i++;
$cfg['Servers'][$i]['auth_type']     = 'cookie';
$cfg['Servers'][$i]['host'] = 'localhost:3308';
$cfg['Servers'][$i]['connect_type'] = 'tcp';
$cfg['Servers'][$i]['compress'] = false;